# This file will be imported automatically
#
esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

##
# You only need to change RX/TX here
uart:
  id:          uart_modbus_hru
  tx_pin:      19
  rx_pin:      22
  baud_rate:   19200
  data_bits:   8
  stop_bits:   1     # Make this 2 if Parity is none
  parity:      EVEN
  debug:
    direction: BOTH
