##
# Replacing the filter should clear the error, but we want to overrride this if the filter is still fine.
number:
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Filter vuil - volumemeting"
    id: HRU_errors1
    register_type: holding
    address: 200
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true
    entity_category: diagnostic
    icon: mdi:air-filter
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Filter vuil - tijdmeting"
    id: HRU_errors2
    register_type: holding
    address: 201 # 0x000E
    value_type: U_WORD
    skip_updates: 10
    use_write_multiple: true
    entity_category: diagnostic
    icon: mdi:air-filter
###
##
# Controlling fan
## By Demand
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Demand ventilation speed" # Sets actual fan speed
    id: HRU_fan_demand_value
    icon: mdi:home-import-outline
    register_type: holding
    address: 2010
    min_value: 0
    max_value: 399
    step: 1
    value_type: U_WORD
    use_write_multiple: true
    on_value_range:
      - above: 2.0
        then: 
          - number.set:
              id: HRU_fan_demand_on_off
              value: 1.0
      - below: 1.0
        then:
          - number.set:
              id: HRU_fan_demand_on_off
              value: 0.0
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Demand ventialtion - on/off" # 0 = auto 1 = Manual
    id: HRU_fan_demand_on_off
    register_type: holding
    address: 2011
    min_value: 0
    max_value: 1
    step: 1
    use_write_multiple: true
    icon: mdi:toggle-switch-variant
## By Flow
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Flow ingress speed" # Sets actual fan speed
    id: HRU_fan_flow_ingress_value
    icon: mdi:home-import-outline
    register_type: holding
    address: 2020
    min_value: 0
    max_value: 399
    step: 1
    value_type: U_WORD
    use_write_multiple: true
    on_value_range:
      - above: 2.0
        then: 
          - number.set:
              id: HRU_fan_flow_ingress_on_off
              value: 1.0
      - below: 1.0
        then:
          - number.set:
              id: HRU_fan_flow_ingress_on_off
              value: 0.0
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Flow ingress - on/off" # 0 = auto 1 = Manual
    id: HRU_fan_flow_ingress_on_off
    register_type: holding
    address: 2021
    min_value: 0
    max_value: 1
    step: 1
    use_write_multiple: true
    icon: mdi:toggle-switch-variant