###
# Select Manual / Auto mode on the WTW Unit
select:
  - platform: modbus_controller
    modbus_controller_id: hru
    id: HRU_fan_flow_ingress_select
    name: "Flow ingress - auto/manual"
    address: 2021
    optionsmap:
      Auto: 0
      Manual: 1
    entity_category: config
  - platform: modbus_controller
    modbus_controller_id: hru
    id: HRU_fan_demand_ingress_select
    name: "Flow demand - auto/manual"
    address: 2011
    optionsmap:
      Auto: 0
      Manual: 1
    entity_category: config
