sensor:
## Info:
# address = register number - 1
##
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Levensduur teller deel 2"
    id: lifetime_counter_part2
    register_type: holding
    address: 4001 
    value_type: U_WORD
    unit_of_measurement: "h"
    skip_updates: 10
    state_class: "total_increasing"
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Hoogste gemeten CO2-concentratie"
    id: hru_co2_maxperc
    register_type: holding
    address: 3011
    value_type: U_WORD
    unit_of_measurement: "ppm"
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Snelheid toevoerventilator "
    id: hru_rpm_toevoerventilator
    register_type: holding
    address: 3020
    value_type: U_WORD
    unit_of_measurement: "rpm"
    device_class: "speed"
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Snelheid afvoerventilator"
    id: hru_rpm_afvoerventilator
    register_type: holding
    address: 3021
    value_type: U_WORD
    unit_of_measurement: "rpm"
    device_class: "speed"
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Werkelijke vermogen voedingsventilator"
    id: hru_pwr_toevoerventilator
    register_type: holding
    address: 3022
    value_type: U_WORD
    unit_of_measurement: "W"
    device_class: "energy"
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Werkelijke vermogen afvoerventilator"
    id: hru_pwr_afvoerventilator
    register_type: holding
    address: 3023
    value_type: U_WORD
    unit_of_measurement: "W" 
    device_class: "energy"
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Volumestroom van buitenaf in m3/h"
    id: hru_m3h_toevoer_external
    register_type: holding
    address: 3030
    value_type: U_WORD
    unit_of_measurement: "m3/h"
    state_class: "measurement"
    device_class: "gas"
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Massastroom van buitenaf in kg/h"
    id: hru_mass_toevoer_external
    register_type: holding
    address: 3031
    value_type: U_WORD
    unit_of_measurement: "kg/h"
  - platform: modbus_controller # 0x91 type, signed 16bit/10
    modbus_controller_id: hru
    name: "Temperatuur van buitenaf"
    id: hru_temp_toevoer_external
    register_type: holding
    address: 3032 
    value_type: S_WORD
    filters:
      - multiply: 0.1
    unit_of_measurement: "°C"
    state_class: "measurement"
    device_class: "temperature"
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Relatieve vochtigheid van buitenaf"
    id: hru_rel_hum_toevoer_external
    register_type: holding
    address: 3033
    value_type: U_WORD
    unit_of_measurement: "%"
    state_class: "measurement"
    device_class: "humidity"
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Volumestroom door vorstklep in m3/h"
    id: hru_m3h_vorstklep
    register_type: holding
    address: 3040
    value_type: U_WORD
    unit_of_measurement: "m3/h"
    state_class: "measurement"
    device_class: "gas"
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Volumestroom gemengd in m3/h"
    id: hru_m3h_toevoer_gemengd
    register_type: holding
    address: 3050
    value_type: U_WORD
    unit_of_measurement: "m3/h"
    state_class: "measurement"
    device_class: "gas"
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Massastroom gemengd in kg/h"
    id: hru_kg_toevoer_gemengd
    register_type: holding
    address: 3051
    value_type: U_WORD
    unit_of_measurement: "kg/h"
    state_class: "measurement"
  - platform: modbus_controller # 0x91 type, signed 16bit/10
    modbus_controller_id: hru
    name: "Temperatuur gemengd "
    id: hru_temp_toevoer_gemengd
    register_type: holding
    address: 3052
    value_type: S_WORD
    filters:
      - multiply: 0.1
    unit_of_measurement: "°C"
    state_class: "measurement"
    device_class: "temperature"
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Relatieve vochtigheid gemengd"
    id: hru_hum_toevoer_gemengd
    register_type: holding
    address: 3053 
    value_type: U_WORD
    unit_of_measurement: "%"
    state_class: "measurement"
    device_class: "humidity"
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Volumestroom naar gebouw in m3/h"
    id: hru_m3h_toevoer_binnen_total
    register_type: holding
    address: 3060 
    value_type: U_WORD
    unit_of_measurement: "m3/h"
    state_class: "measurement"
    device_class: "gas"
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Massastroom naar gebouw in kg/h"
    id: hru_kgh_toevoer_binnen_total
    register_type: holding
    address: 3061 
    value_type: U_WORD
    unit_of_measurement: "kg/h"
    state_class: "measurement"
  - platform: modbus_controller # 0x91 type, signed 16bit/10
    modbus_controller_id: hru
    name: "Temperatuur naar gebouw"
    id: hru_temp_naar_binnen
    register_type: holding
    address: 3062
    value_type: S_WORD
    filters:
      - multiply: 0.1
    unit_of_measurement: "°C"
    state_class: "measurement"
    device_class: "temperature"
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Relatieve vochtigheid naar gebouw"
    id: hru_rel_hum_toevoer
    register_type: holding
    address: 3063 
    value_type: U_WORD
    unit_of_measurement: "%"
    state_class: "measurement"
    device_class: "humidity"
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Volumestroom van gebouw in m3/h"
    id: hru_m3h_afvoer_binnen
    register_type: holding
    address: 3070 
    value_type: U_WORD
    unit_of_measurement: "m3/h"
    state_class: "measurement"
    device_class: "gas"
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Massastroom van gebouw in kg/h"
    id: hru_kgh_afvoer_binnen
    register_type: holding
    address: 3071 
    value_type: U_WORD
    unit_of_measurement: "kg/h"
    state_class: "measurement"
  - platform: modbus_controller # 0x91 type, signed 16bit/10
    modbus_controller_id: hru
    name: "Temperatuur van gebouw"
    id: hru_temp_binnen
    register_type: holding
    address: 3072 
    value_type: S_WORD
    filters:
      - multiply: 0.1
    unit_of_measurement: "°C"
    state_class: "measurement"
    device_class: "temperature"
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Relatieve vochtigheid van gebouw in %"
    id: hru_rel_hum_binnen
    register_type: holding
    address: 3073
    value_type: U_WORD
    unit_of_measurement: "%"
    state_class: "measurement"
    device_class: "humidity"
    filters:
      - or:
          - delta: 1
          - heartbeat: 60s
      - lambda: 
          float rand1 = rand() % 1;        
          return x + rand1;
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Volumestroom naar buiten in m3/h"
    id: hru_m3h_afvoer_buiten
    register_type: holding
    address: 3080
    value_type: U_WORD
    unit_of_measurement: "m3/h"
    state_class: "measurement"
    device_class: "gas"
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Massastroom naar buiten in kg/h"
    id: hru_kgh_afvoer_buiten
    register_type: holding
    address: 3081 
    value_type: U_WORD
    unit_of_measurement: "kg/h"
    state_class: "measurement"
  - platform: modbus_controller # 0x91 type, signed 16bit/10
    modbus_controller_id: hru
    name: "Temperatuur naar buiten "
    id: hru_temp_afvoer_buiten
    register_type: holding
    address: 3082
    value_type: S_WORD
    filters:
    - multiply: 0.1
    unit_of_measurement: "°C"
    state_class: "measurement"
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Relatieve vochtigheid naar buiten "
    id: hru_hum_afvoer_buiten
    register_type: holding
    address: 3083
    value_type: U_WORD
    unit_of_measurement: "%"
    state_class: "measurement"
    device_class: "humidity"
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Mengstroom teller deel 2"
    id: mixflow_counter_part2
    register_type: holding
    address: 4003 
    value_type: U_WORD
    unit_of_measurement: "m3"
    skip_updates: 10
    state_class: "total_increasing"
    device_class: "gas"

#number:
# These used to be numbers, but you should not have to reset these. 
# Fix the error and the number will disappear accorting to the manual.
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Flow - afvoervolume"
    id: HRU_errors3
    register_type: holding
    address: 202 # 0x000E
    value_type: U_WORD
    skip_updates: 10
    #use_write_multiple: true
    entity_category: diagnostic
    icon: mdi:alert-circle
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Flow - toevoervolume"
    id: HRU_errors4
    register_type: holding
    address: 203 # 0x000E
    value_type: U_WORD
    skip_updates: 10
    #use_write_multiple: true
    entity_category: diagnostic
    icon: mdi:alert-circle
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Fout - Vochtsensor Intern"
    id: HRU_errors11
    register_type: holding
    address: 210 # 0x000E
    value_type: U_WORD
    skip_updates: 10
    #use_write_multiple: true
    entity_category: diagnostic
    icon: mdi:alert-circle
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Fout - Vochtsensor afvoer"
    id: HRU_errors12
    register_type: holding
    address: 211 # 0x000E
    value_type: U_WORD
    skip_updates: 10
    #use_write_multiple: true
    entity_category: diagnostic
    icon: mdi:alert-circle
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Fout - Vochtsensor toevoer"
    id: HRU_errors13
    register_type: holding
    address: 212 # 0x000E
    value_type: U_WORD
    skip_updates: 10
    #use_write_multiple: true
    entity_category: diagnostic
    icon: mdi:alert-circle
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Fout - Temperatuur sensor intern"
    id: HRU_errors14
    register_type: holding
    address: 213 # 0x000E
    value_type: U_WORD
    skip_updates: 10
    #use_write_multiple: true
    entity_category: diagnostic
    icon: mdi:alert-circle
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Fout - Temperatuur sensor afvoer"
    id: HRU_errors15
    register_type: holding
    address: 214 # 0x000E
    value_type: U_WORD
    skip_updates: 10
    #use_write_multiple: true
    entity_category: diagnostic
    icon: mdi:alert-circle
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Fout - Temperatuur sensor toevoer"
    id: HRU_errors16
    register_type: holding
    address: 215 # 0x000E
    value_type: U_WORD
    skip_updates: 10
    #use_write_multiple: true
    entity_category: diagnostic
    icon: mdi:alert-circle
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Fout - bypassklep"
    id: HRU_errors21
    register_type: holding
    address: 220 # 0x000E
    value_type: U_WORD
    skip_updates: 10
    #use_write_multiple: true
    entity_category: diagnostic
    icon: mdi:alert-circle
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Fout - vorstklep"
    id: HRU_errors22
    register_type: holding
    address: 221 # 0x000E
    value_type: U_WORD
    skip_updates: 10
    #use_write_multiple: true
    entity_category: diagnostic
    icon: mdi:alert-circle
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Fout - Electracompartiment"
    id: HRU_errors23
    register_type: holding
    address: 222 # 0x000E
    value_type: U_WORD
    skip_updates: 10
    #use_write_multiple: true
    entity_category: diagnostic
    icon: mdi:alert-circle
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Fout - volumesensor toevoer"
    id: HRU_errors31
    register_type: holding
    address: 230 # 0x000E
    value_type: U_WORD
    skip_updates: 10
    #use_write_multiple: true
    entity_category: diagnostic
    icon: mdi:alert-circle
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Fout - volumesensor afvoer"
    id: HRU_errors32
    register_type: holding
    address: 231 # 0x000E
    value_type: U_WORD
    skip_updates: 10
    #use_write_multiple: true
    entity_category: diagnostic
    icon: mdi:alert-circle
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Fout - ventilator module afvoer"
    id: HRU_errors33
    register_type: holding
    address: 232 # 0x000E
    value_type: U_WORD
    skip_updates: 10
    #use_write_multiple: true
    entity_category: diagnostic
    icon: mdi:alert-circle
  - platform: modbus_controller
    modbus_controller_id: hru
    name: "Fout - ventilator module toevoer"
    id: HRU_errors34
    register_type: holding
    address: 233 # 0x000E
    value_type: U_WORD
    skip_updates: 10
    #use_write_multiple: True
    entity_category: diagnostic
    icon: mdi:alert-circle